name: Spring PetClinic CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  JFROG_PLATFORM_URL: ${{ secrets.JFROG_PLATFORM_URL }}
  JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
  JFROG_ACCESS_TOKEN: ${{ secrets.JFROG_ACCESS_TOKEN }}

  MAVEN_VIRTUAL_REPO: maven-virtual
  DOCKER_LOCAL_REPO: docker-hub-local
  DOCKER_VIRTUAL_REPO: docker-hub-virtual
  IMAGE_NAME: spring-petclinic
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Install JFrog CLI & Configure Server
      run: |
        curl -fL https://install-cli.jfrog.io | sh
        jf --version

        echo "DOCKER_REGISTRY_HOST=$(echo ${{ env.JFROG_PLATFORM_URL }} | sed 's|^https://||')" >> $GITHUB_ENV

        jf c add main-jfrog-server --url=${{ env.JFROG_PLATFORM_URL }} --user=${{ env.JFROG_USERNAME }} --access-token=${{ env.JFROG_ACCESS_TOKEN }} --overwrite --interactive=false

    - name: Configure Maven for JFrog Artifactory
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml <<EOF
        <settings>
            <servers>
                <server>
                    <id>${{ env.MAVEN_VIRTUAL_REPO }}</id>
                    <username>${{ env.JFROG_USERNAME }}</username>
                    <password>${{ env.JFROG_ACCESS_TOKEN }}</password>
                </server>
            </servers>
            <profiles>
                <profile>
                    <id>artifactory</id>
                    <repositories>
                        <repository>
                            <id>${{ env.MAVEN_VIRTUAL_REPO }}</id>
                            <name>${{ env.MAVEN_VIRTUAL_REPO }}</name>
                            <url>${{ env.JFROG_PLATFORM_URL }}/artifactory/${{ env.MAVEN_VIRTUAL_REPO }}</url>
                            <snapshots>
                                <enabled>true</enabled>
                            </snapshots>
                        </repository>
                    </repositories>
                    <pluginRepositories>
                        <pluginRepository>
                            <id>${{ env.MAVEN_VIRTUAL_REPO }}</id>
                            <name>${{ env.MAVEN_VIRTUAL_REPO }}</name>
                            <url>${{ env.JFROG_PLATFORM_URL }}/artifactory/${{ env.MAVEN_VIRTUAL_REPO }}</url>
                            <snapshots>
                                <enabled>true</enabled>
                            </snapshots>
                        </pluginRepository>
                    </pluginRepositories>
                </profile>
            </profiles>
            <activeProfiles>
                <activeProfile>artifactory</activeProfile>
            </activeProfiles>
        </settings>
        EOF

    - name: Compile the code
      run: mvn clean compile

    - name: Run the tests
      run: mvn test

    - name: Package the project (JAR)
      run: mvn package -DskipTests

    - name: Build Docker image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_LOCAL_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    - name: Publish Docker image to JFrog Artifactory
      run: |
        jf rt docker-push ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_LOCAL_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_LOCAL_REPO }}

    - name: Trigger JFrog XRay Scan
      run: |
        jf rt curl -XPOST "/xray/api/v1/scan/artifact" -H "Content-Type: application/json" -d '{
          "repo_path": "${{ env.DOCKER_LOCAL_REPO }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/manifest.json", # Ensure this exact path is scanned
          "watches": ["${{ secrets.YOUR_XRAY_WATCH_NAME }}"]
        }'
        echo "XRay scan triggered for ${{ env.DOCKER_LOCAL_REPO }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}"
        sleep 120 # Delay for XRay processing

    - name: Get XRay Scan Data (using Export API)
      run: |
        # Construct the artifact ID (repo_path)
        ARTIFACT_ID="${{ env.DOCKER_LOCAL_REPO }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/manifest.json"

        # Construct the JSON payload for the export API
        EXPORT_PAYLOAD=$(jq -n \
            --arg id "$ARTIFACT_ID" \
            '{artifact_id: $id, include_licenses: true, include_vulnerabilities: true, include_security_violations: true, include_policy_violations: true, output_format: "json"}'
        )

        # Execute the curl command to download the XRay JSON data
        # Note: This API takes a POST request with a JSON body
        jf rt curl -XPOST "/xray/api/v1/export/artifact" \
           -H "Content-Type: application/json" \
           -d "$EXPORT_PAYLOAD" \
           -o xray_scan_data.json
      continue-on-error: true

    - name: Upload XRay Scan Data as artifact
      if: success() && github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: xray-scan-data
        path: xray_scan_data.json
